#!/usr/bin/env python
"""Run tests in src/tests"""
# global imports
import unittest

if __name__ == '__main__':
    testsuite = unittest.TestLoader().discover('.')
    unittest.TextTestRunner(verbosity=2).run(testsuite)